SELECT TOP (1000) [UniqueID]
      ,[YEAR]
      ,[DRIVERPOSITION]
      ,[drivernumber]
      ,[trackname]
      ,[drivername]
      ,[driver nametag]
      ,[driverteam]
      ,[laps]
      ,[totak race time]
      ,[Points]
  FROM [Formula1].[rpt].[vw_RaceResults]
